#!/usr/bin/env python3
"""Generates the 16x16 item textures from ASCII art. Deterministic — rerun
after editing the art below and the PNGs in assets/ are rewritten."""

import struct
import zlib
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "assets" / "vhlite" / "textures" / "item"

# Shared palette: char -> RGBA. '.' is transparent.
PALETTE = {
    ".": (0, 0, 0, 0),
    # purples (crystal / altar)
    "A": (216, 160, 255, 255),
    "B": (170, 90, 235, 255),
    "C": (110, 40, 180, 255),
    # teals (essence)
    "T": (60, 220, 210, 255),
    "U": (20, 150, 150, 255),
    "V": (10, 90, 100, 255),
    # cyans / whites (star, feather)
    "W": (255, 255, 255, 255),
    "X": (150, 230, 255, 255),
    "Y": (70, 170, 220, 255),
    # magentas (catalyst)
    "M": (255, 110, 230, 255),
    "N": (190, 40, 170, 255),
    "O": (120, 10, 110, 255),
    # browns / golds (backpack, crate, wand)
    "b": (140, 95, 55, 255),
    "d": (95, 60, 30, 255),
    "e": (60, 35, 15, 255),
    "g": (250, 200, 70, 255),
    "h": (190, 140, 30, 255),
    # greens (balm)
    "G": (120, 230, 120, 255),
    "H": (50, 160, 70, 255),
    "I": (20, 100, 45, 255),
    # reds / oranges (warcry)
    "R": (255, 90, 60, 255),
    "S": (220, 40, 30, 255),
    "Q": (255, 190, 70, 255),
    # greys (altar stone)
    "s": (150, 150, 155, 255),
    "t": (105, 105, 112, 255),
    "u": (65, 65, 72, 255),
}

ART = {
    "vault_crystal": """
................
.......AB.......
......ABBC......
.....ABWBCC.....
....ABWBBBCC....
....ABBBBBCC....
...ABBBBBBCCC...
...ABBBBBBCCC...
....ABBBBCCC....
....ABBBCCCC....
.....ABBCCC.....
......ABCC......
.......AC.......
................
................
................
""",
    "vault_essence": """
................
......T.........
.....TUT........
.....TUUT.......
....TUUUV.......
....TUWUUV......
...TUUUUUV......
...TUUUUUVV.....
....TUUUVV......
....TUUVV.......
.....TUV........
.....TV.........
......V.........
................
................
................
""",
    "knowledge_star": """
................
.......X........
.......XX.......
......XWX.......
......XWXX......
..XXXXWWWXXXX...
...XXWWWWWXX....
....XWWWWWX.....
...XXWWWWWXX....
..XXXXWWWXXXX...
......XWXX......
......XWX.......
.......XX.......
.......X........
................
................
""",
    "catalyst": """
................
.....MMNN.......
....MWWMNN......
...MWMMMNNN.....
...MWMNNMNN.....
..MMMNNOONNN....
..MMNNOMMONN....
..MNNOMMMONN....
..MNNOMMONNN....
..MNNOOOONNN....
...MNNNNNNN.....
...MMNNNNNN.....
....MMNNNN......
.....MMNN.......
................
................
""",
    "backpack": """
................
.....ddd........
....dbbbd.......
...dbbbbbd......
..dbdddddbd.....
..dbbbbbbbde....
..dbbbbbbbde....
..dbgbbbbgde....
..dbgbbbbgde....
..dbbdddbbde....
..dbbdedbbde....
..dbbbbbbbde....
...dbbbbbde.....
....ddddde......
................
................
""",
    "link_wand": """
................
............XW..
...........XWX..
..........hgX...
.........hgg....
........hgg.....
.......hgg......
......hgg.......
.....hgg........
....hgg.........
...hgg..........
..hgg...........
..hg............
..h.............
................
................
""",
    "vault_balm": """
................
......ddd.......
......dgd.......
.....dddd.......
....dGGGHd......
...dGWGGHHd.....
...dGGGGHHd.....
...dGGGHHHd.....
...dGGHHHId.....
...dGHHHIId.....
...dHHHIIId.....
....dHHIId......
.....dddd.......
................
................
................
""",
    "windstep": """
................
..........XW....
.........XWW....
........XWWX....
.......XWWX.....
......XWWWX.....
.....XWWWX......
....XWWWWX......
....XWWWX.......
...XWWWX........
...XWWX.........
..XWXX..........
..XX............
..X.............
................
................
""",
    "warcry": """
................
.......R........
......RR........
......RRS.......
...R.RRQS.......
...RRRQQS.......
..RRQQQQSS......
..RQQWQQSS......
..RQQWWQSS......
..RRQQQQSS......
...RRQQSS.......
....RRSS........
.....RS.........
................
................
................
""",
    "vault_altar": """
................
................
.......B........
......ABC.......
......ABC.......
.....AABCC......
..ssssssssss....
..stttttttts....
..sttBBBttts....
..sttBBBttts....
..stttttttts....
..suuuuuuuus....
..suuuuuuuus....
..ssssssssss....
................
................
""",
    "vault_crate": """
................
..eeeeeeeeeee...
..egggggggge....
..ebbddbbdbe....
..ebddbbddbe....
..egggggggge....
..ebbdbbddbe....
..ebdbbdbbbe....
..ebbddbbdbe....
..egggggggge....
..ebdbbddbbe....
..ebbdbbdbbe....
..egggggggge....
..eeeeeeeeeee...
................
................
""",
}


def write_png(path: Path, rows: list[str]) -> None:
    raw = b""
    for row in rows:
        raw += b"\x00"  # filter: none
        for ch in row:
            raw += struct.pack("4B", *PALETTE[ch])

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", struct.pack(">IIBBBBB", 16, 16, 8, 6, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(raw))
           + chunk(b"IEND", b""))
    path.write_bytes(png)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, art in ART.items():
        rows = [line for line in art.strip("\n").split("\n")]
        assert len(rows) == 16, f"{name}: {len(rows)} rows"
        for row in rows:
            assert len(row) == 16, f"{name}: row '{row}' is {len(row)} wide"
        write_png(OUT / f"{name}.png", rows)
        print(f"wrote {name}.png")


if __name__ == "__main__":
    main()
